### ISSUE TITLE
"Cannot find module '.\reporters\gherkin'" on Windows

### ISSUE THREAD

**Issue by kjwenger** [telefonicaid/tartare#38]
tartare.js:129

```
//    _reporter = require('.' + path.sep + path.join('reporters', reporter)); // Causes error
//     _reporter = require(path.resolve(__dirname, 'reporters', reporter)); // Possible fix
    _reporter = require(__dirname + path.sep + path.join('reporters', reporter)); // Possible fix
```

**Comment by JoseAntonioRodriguez** [comment]
Thank you @kjwenger for the tip. I don't have a lot of time for this just now, but I'll take a look as soon as possible.

**Comment by kjwenger** [comment]
please find attached a patch file. cheers!

[fix_for___38__Cannot_find_module____reporters_gherkin___on_Windows.patch.zip](https://github.com/telefonicaid/tartare/files/899898/fix_for___38__Cannot_find_module____reporters_gherkin___on_Windows.patch.zip)

**Comment by JoseAntonioRodriguez** [comment]
Thank you @kjwenger. I'll release your patch today.
